name: food_ui
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/picture/



  fonts:
     - family: Signika
       fonts:
         - asset: assets/fonts/SignikaNegative-Bold.ttf
           weight: 700
         - asset: assets/fonts/SignikaNegative-Light.ttf
           weight: 300
         - asset: assets/fonts/SignikaNegative-Medium.ttf
           weight: 500
         - asset: assets/fonts/SignikaNegative-Regular.ttf
           weight: 400
         - asset: assets/fonts/SignikaNegative-SemiBold.ttf
           weight: 600
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

